package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "Usage: go2ts <typescript_file.ts> <./go_package1> [./go_package2] ...\n")
		os.Exit(1)
	}

	outputFile := os.Args[1]
	packagePaths := os.Args[2:]

	// Collect all Go package directories
	var dirs []string
	for _, pkgPath := range packagePaths {
		if strings.HasSuffix(pkgPath, "/...") {
			baseDir := strings.TrimSuffix(pkgPath, "/...")
			found, err := findGoDirs(baseDir)
			if err != nil {
				fmt.Fprintf(os.Stderr, "error walking %s: %v\n", baseDir, err)
				os.Exit(1)
			}
			dirs = append(dirs, found...)
		} else {
			dirs = append(dirs, pkgPath)
		}
	}

	// Parse packages and collect TypeScript type definitions
	var sb strings.Builder
	sb.WriteString("// Code generated by go2ts. DO NOT EDIT.\n\n")

	seen := map[string]bool{}
	for _, dir := range dirs {
		types, err := parsePackage(dir)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error parsing package %s: %v\n", dir, err)
			os.Exit(1)
		}
		for _, t := range types {
			if seen[t.name] {
				continue
			}
			seen[t.name] = true
			sb.WriteString(t.toTypeScript())
			sb.WriteString("\n")
		}
	}

	if err := os.WriteFile(outputFile, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing output file: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s\n", outputFile)
}

// findGoDirs recursively walks baseDir and returns all sub-directories
// (including baseDir itself) that contain at least one .go file.
func findGoDirs(baseDir string) ([]string, error) {
	var dirs []string
	err := filepath.WalkDir(baseDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			entries, err := os.ReadDir(path)
			if err != nil {
				return err
			}
			for _, e := range entries {
				if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") {
					dirs = append(dirs, path)
					break
				}
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return dirs, nil
}

// tsType represents a TypeScript type generated from a Go struct.
type tsType struct {
	name   string
	fields []tsField
}

type tsField struct {
	name     string
	tsType   string
	nullable bool
	optional bool // omitempty
}

func (t *tsType) toTypeScript() string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("export type %s = {\n", t.name))
	for _, f := range t.fields {
		typ := f.tsType
		if f.nullable {
			typ = typ + " | null"
		}
		if f.optional {
			sb.WriteString(fmt.Sprintf("  %s?: %s,\n", f.name, typ))
		} else {
			sb.WriteString(fmt.Sprintf("  %s: %s,\n", f.name, typ))
		}
	}
	sb.WriteString("}")
	return sb.String()
}

// parsePackage parses all Go files in dir and returns tsType entries for each exported struct.
func parsePackage(dir string) ([]tsType, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		// skip test files
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		return nil, err
	}

	// Sort package names for deterministic output
	pkgNames := make([]string, 0, len(pkgs))
	for name := range pkgs {
		pkgNames = append(pkgNames, name)
	}
	sort.Strings(pkgNames)

	var result []tsType
	for _, pkgName := range pkgNames {
		pkg := pkgs[pkgName]

		// Sort file names for deterministic output
		fileNames := make([]string, 0, len(pkg.Files))
		for name := range pkg.Files {
			fileNames = append(fileNames, name)
		}
		sort.Strings(fileNames)

		for _, fileName := range fileNames {
			file := pkg.Files[fileName]
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}
					// Only export types that start with uppercase
					if !ast.IsExported(typeSpec.Name.Name) {
						continue
					}
					t, err := convertStruct(typeSpec.Name.Name, structType)
					if err != nil {
						return nil, fmt.Errorf("converting struct %s: %w", typeSpec.Name.Name, err)
					}
					if t != nil {
						result = append(result, *t)
					}
				}
			}
		}
	}
	return result, nil
}

// convertStruct converts a Go AST struct type into a tsType.
func convertStruct(name string, s *ast.StructType) (*tsType, error) {
	t := &tsType{name: name}
	for _, field := range s.Fields.List {
		jsonName, omitempty, skip := parseJSONTag(field.Tag)
		if skip {
			continue
		}
		// If there's no json tag, use the Go field name as-is
		// (matches encoding/json default behaviour)
		if jsonName == "" {
			if len(field.Names) == 0 {
				// Embedded struct — skip for now
				continue
			}
			if !ast.IsExported(field.Names[0].Name) {
				continue
			}
			jsonName = field.Names[0].Name
		}

		nullable, tsTypeName := goTypeToTS(field.Type)

		t.fields = append(t.fields, tsField{
			name:     jsonName,
			tsType:   tsTypeName,
			nullable: nullable,
			optional: omitempty,
		})
	}
	return t, nil
}

// parseJSONTag extracts the JSON field name and flags from a struct tag.
// Returns ("", false, true) when the field should be skipped (json:"-").
func parseJSONTag(tag *ast.BasicLit) (name string, omitempty bool, skip bool) {
	if tag == nil {
		return "", false, false
	}
	// Strip surrounding backticks
	raw := tag.Value
	if len(raw) >= 2 && raw[0] == '`' {
		raw = raw[1 : len(raw)-1]
	}
	st := reflect.StructTag(raw)
	jsonTag := st.Get("json")
	if jsonTag == "" {
		return "", false, false
	}
	parts := strings.Split(jsonTag, ",")
	jsonName := parts[0]
	if jsonName == "-" {
		return "", false, true
	}
	for _, p := range parts[1:] {
		if p == "omitempty" {
			omitempty = true
		}
	}
	return jsonName, omitempty, false
}

// goTypeToTS converts a Go AST expression to a TypeScript type string.
// The bool return value indicates whether the type is nullable (i.e. was a pointer).
func goTypeToTS(expr ast.Expr) (nullable bool, tsTypeName string) {
	switch t := expr.(type) {
	case *ast.Ident:
		return false, identToTS(t.Name)
	case *ast.StarExpr:
		_, inner := goTypeToTS(t.X)
		return true, inner
	case *ast.SelectorExpr:
		return false, selectorToTS(t)
	case *ast.ArrayType:
		// []byte is a special case → string (base64)
		if ident, ok := t.Elt.(*ast.Ident); ok && ident.Name == "byte" {
			return false, "string"
		}
		_, elemType := goTypeToTS(t.Elt)
		return false, "Array<" + elemType + ">"
	case *ast.MapType:
		_, valueType := goTypeToTS(t.Value)
		return false, "{ [key: string]: " + valueType + " }"
	case *ast.InterfaceType:
		return false, "any"
	default:
		return false, "any"
	}
}

// identToTS maps a Go built-in type name to its TypeScript equivalent.
func identToTS(name string) string {
	switch name {
	case "string":
		return "string"
	case "bool":
		return "boolean"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"byte", "rune":
		return "number"
	case "error":
		return "string"
	default:
		// Unknown named type (local type alias, enum, etc.)
		return name
	}
}

// selectorToTS maps qualified Go types (pkg.Type) to TypeScript equivalents.
func selectorToTS(t *ast.SelectorExpr) string {
	pkgIdent, ok := t.X.(*ast.Ident)
	if !ok {
		return "any"
	}
	pkg := pkgIdent.Name
	typ := t.Sel.Name
	switch pkg {
	case "time":
		return "string"
	case "uuid", "guid":
		return "string"
	case "decimal", "big":
		return "string"
	default:
		// Return just the type name; cross-package types become their own TS name
		return typ
	}
}

