alias gs="git status"
alias ga="git add"
alias gu="git add -u"
alias gm="git commit -m"
alias gp="git push"

export GOROOT="/usr/local/go"
export GOPATH="$HOME/.local/gopath"
export GOPROXY=direct
export GOTOOLCHAIN="local"
go telemetry off

export TZ="UTC"
export DO_NOT_TRACK=1
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
