package crypto

import (
	"testing"
)

func TestRandBytes(t *testing.T) {
	var n uint64 = 42

	data := RandBytes(n)

	if len(data) != int(n) {
		t.Error("Generated bytes buffer is not at the expected size")
	}
}
